### ISSUE TITLE
Review of pricing simulations notebook

### ISSUE THREAD

**Issue by rcolle** [atoti/notebooks#17]
I had several remarks that I shared with @jbe456 about https://github.com/atoti/notebooks/tree/master/retail/pricing-simulations-around-product-classes

- [x] Why did you immediately disable sampling when creating the session?
1. That's definitely not a best practice
2. If you were to do so, there is a session configuration parameter instead of calling the `load_all_data` method. But I really insist that it shouldn't be disable until actually needed.
- [x] Also, why use markdown to display links? Links are automatically displayed in jupyter notebooks and in jupyter lab >=2
- [x] Why clean the output of all cells except the `cube.visualize` ones (which are useless)?
- [x] Do you really need to publish the Price index numerator measure?
- [x] Why do you always use pandas to read csv data, even when not needed? Moreover, as far as I know, `long` is not a valid dtype in pandas. You can use `int64` if needed, but I'm not sure this is necessary here.
- [x] The notebook is very badly formatted. Could you please run a PEP8 compliant formatting tool? Within `atoti` we do it this way: https://github.com/activeviam/atoti/blob/673a3560b4dbabb100eb730fd5e3f05f2a405196/javascript/cli/src/commands/test/notebooks.ts

I haven't reviewed the other notebooks, but it's likely that some of the comments could also be applied.

**Comment by SamTaz** [comment]
Hello Romain, thank you for the feedback.

I have adjusted everything accordingly, except for the sampling because of two reasons:
- The main reason is I don't see the need for sampling on a notebook that is already finished. Just a few cells below the `atoti.create_session` we have our first `cube.visualize` where we need all the data to plot the correct result. Do you still recommend we use session.load_all_data at the last possible moment help with best practices ?
In any case I added a comment in the cell where we create the session to advise using sampling when building the notebook.
- Second reason is I tried the `create_session` with sampling_mode="FULL" and got some bugs when trying to load stores, I'll raise an issue.

For the rest we will be using black on all cells for now, and we only cleaned the session.url outputs since the link can be different from a session to another, most of the other cells simply do not generate outputs.

**Comment by rcolle** [comment]
> * The main reason is I don't see the need for sampling on a notebook that is already finished. Just a few cells below the `atoti.create_session` we have our first `cube.visualize` where we need all the data to plot the correct result. Do you still recommend we use session.load_all_data at the last possible moment to help conveying best practices ?
>   In any case I added a comment in the cell where we create the session to advise using sampling when building the notebook.

Do you have more data than the default sampling size? If not I'd just remove any mention to sampling.

**Comment by SamTaz** [comment]
Yes, most stores have more than 10k lines.

**Comment by rcolle** [comment]
What's the size then? And where do these files come from (generated, actual data).
Depending on this, we can either reduce your file size or maybe adjust the default sampling limit.

**Comment by jbe456** [comment]
Apart from the sampling limit (for which we added a comment), all issues have been addressed as requested.
